### ISSUE TITLE
Plugin installation failed in Cider

### ISSUE THREAD

**Issue by ahloiscreamo** [tnguye20/cider-polybar#1]
Hello, the plugin did not install through cider explore plugins,

can you guide me how to install and launch the polybar module manually?
Thanks in advance!
![Screenshot from 2022-07-13 17-03-31](https://user-images.githubusercontent.com/9318372/178695571-b337cde3-b38a-475b-9c54-bcd1f570cc2a.png)

**Comment by tnguye20** [comment]
Hi, I actually don't know how Cider pull the README.md in, but I will push an update version with a snippet of my polybar config which has it configured.
